# Generated by Django 2.0.3 on 2018-09-10 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=64)),
                ('street', models.CharField(max_length=64, null=True)),
                ('house_no', models.IntegerField()),
                ('flat_no', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(max_length=64)),
                ('email_type', models.IntegerField(choices=[(0, 'brak informacji'), (1, 'prywatny'), (2, 'służbowy'), (3, 'inny')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=128, null=True)),
                ('image', models.ImageField(blank=True, upload_to='home/witek/Desktop/Warsztaty4/Warsztaty4/Warsztaty4/mail_box/Photos/')),
                ('adres', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mail_box.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph_number', models.CharField(max_length=32)),
                ('ph_type', models.IntegerField(choices=[(0, 'brak informacji'), (1, 'komórkowy'), (2, 'domowy'), (3, 'służbowy'), (4, 'inny')], default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail_box.Person')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='persons',
            field=models.ManyToManyField(to='mail_box.Person'),
        ),
        migrations.AddField(
            model_name='email',
            name='e_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail_box.Person'),
        ),
    ]
