# Generated by Django 2.0.3 on 2018-09-10 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_box', '0002_auto_20180910_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='flat_no',
        ),
        migrations.RemoveField(
            model_name='address',
            name='house_no',
        ),
    ]
